# Generated by Django 5.2.1 on 2025-05-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Usina',
                'verbose_name_plural': 'Usinas',
            },
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, verbose_name='Identificador')),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversores', to='production.usina', verbose_name='Usina')),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
                'unique_together': {('usina', 'identificador')},
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Data e Hora')),
                ('potencia', models.FloatField(verbose_name='Potência (W)')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='production.inversor', verbose_name='Inversor')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='production__timesta_c6cc32_idx'), models.Index(fields=['inversor', 'timestamp'], name='production__inverso_90f991_idx')],
            },
        ),
    ]
